platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

def plugins_pods
  source 'https://gitlab.linphone.org/BC/public/podspec.git'
  pod 'linphone-sdk', '5.2.0-alpha.156+e3f28405'
  pod 'linphone-sdk/basic-frameworks', '~> 5.2.0-alpha.156+e3f28405'
  pod 'linphone-sdk/app-extension-swift', '~> 5.2.0-alpha.156+e3f28405'
end

target 'Plugin' do
  capacitor_pods
  plugins_pods
end

target 'PluginTests' do
  capacitor_pods
  plugins_pods
end
